# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7844da3f53aebfe512943a76eae4628bc5eeea5faf3857f3f32d46c13b7e8ccd22f7b2287e438240db907d7ec1ee8841ee0a9d969bf09408870a81e65ebe62b9

test:
  secret_key_base: 339faf3cc53897d2ff2ac5c64f15c3b8f0aa50fa87205ff98a11fed933c96e1617a02c9eb650db953aa387c5a91b277e9a05f1f492d9fe8b8d38eea7ba64976e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
